//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_faq_tbl
    {
        public int pk_faq_id { get; set; }
        public string que { get; set; }
        public string ans { get; set; }
    }
}
