//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_blog_tbl
    {
        public int pk_blog_id { get; set; }
        public string blog_desc { get; set; }
        public string subject { get; set; }
        public string fk_email_id { get; set; }
        public string blog_image { get; set; }
        public System.DateTime blog_date_ { get; set; }
    }
}
