//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_testimonials_tbl
    {
        public int Id { get; set; }
        public string fk_email_id { get; set; }
        public string desc { get; set; }
        public System.DateTime date { get; set; }
        public string photo { get; set; }
        public string status { get; set; }
    }
}
