//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_event_tbl
    {
        public int pk_event_id { get; set; }
        public string event_name { get; set; }
        public string event_desc { get; set; }
        public string speaker { get; set; }
        public string topic { get; set; }
        public string event_img { get; set; }
        public System.DateTime event_date_ { get; set; }
        public System.TimeSpan event_time { get; set; }
        public string event_place { get; set; }
    }
}
