//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_question_tbl
    {
        public int pk_que_id { get; set; }
        public string que_title { get; set; }
        public string que_desc { get; set; }
        public string que_img { get; set; }
        public string fk_email_id { get; set; }
        public Nullable<int> fk_grp_id { get; set; }
        public Nullable<System.DateTime> que_date { get; set; }
    }
}
