//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_material_tbl
    {
        public int pk_material_id { get; set; }
        public string fk_email_id { get; set; }
        public string material_name { get; set; }
        public string material_path { get; set; }
        public Nullable<System.DateTime> material_date { get; set; }
        public string type_of_material { get; set; }
        public int status { get; set; }
    }
}
