//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class and_our_work_tbl
    {
        public int pk_our_work_id { get; set; }
        public string our_work_image { get; set; }
        public string project_name { get; set; }
        public string project_desc { get; set; }
        public Nullable<int> team_size { get; set; }
        public string members_name { get; set; }
        public string days_to_complete { get; set; }
        public string type { get; set; }
        public string platform { get; set; }
        public string link { get; set; }
    }
}
