//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jinalshah_coaching_class.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<and_album_tbl> and_album_tbl { get; set; }
        public DbSet<and_answer_tbl> and_answer_tbl { get; set; }
        public DbSet<and_blog_tbl> and_blog_tbl { get; set; }
        public DbSet<and_comment_tbl> and_comment_tbl { get; set; }
        public DbSet<and_event_tbl> and_event_tbl { get; set; }
        public DbSet<and_faq_tbl> and_faq_tbl { get; set; }
        public DbSet<and_gallery_tbl> and_gallery_tbl { get; set; }
        public DbSet<and_material_tbl> and_material_tbl { get; set; }
        public DbSet<and_news_tbl> and_news_tbl { get; set; }
        public DbSet<and_our_work_tbl> and_our_work_tbl { get; set; }
        public DbSet<and_question_tbl> and_question_tbl { get; set; }
        public DbSet<and_testimonials_tbl> and_testimonials_tbl { get; set; }
        public DbSet<and_user_tbl> and_user_tbl { get; set; }
    }
}
